# OI pixel forest: 300 trees, 22 features, .bin md5 87ab5578978d4fdc4fe0815cc223140b
# generated by forest_pipeline.py; paste into HLTrigger/Configuration/python/HLT_75e33/modules/hltPhase2L3OIMuonTrackSelectionHighPurityForest_cfi.py
modelPath = cms.FileInPath('RecoMuon/L3TrackFinder/data/OI/muonHP_OI_pixelPath_forest_v3.bin'),
decisionThreshold = cms.double(0.27376416325569153),
ptBinEdges = cms.vdouble(0.0, 2.0, 5.0, 10.0, 50.0, 200.0),
decisionThresholds = cms.vdouble(
    0.1006140485405922,  # pT [0, 2)
    0.27376416325569153,  # pT [2, 5)
    0.276641845703125,  # pT [5, 10)
    0.3339681029319763,  # pT [10, 50)
    0.3438858985900879,  # pT [50, 200)
    0.5035520195960999,  # pT [200, inf)
)
nFeatures = cms.int32(22),
