# IO pixel forest: 800 trees, 33 features, .bin md5 51a79055ff06afb9ed3e26ff35ff11c8
# generated by forest_pipeline.py; paste into HLTrigger/Configuration/python/HLT_75e33/modules/hltPhase2MuonPixelTracksHighPurityForest_cfi.py
modelPath = cms.FileInPath('RecoMuon/L3TrackFinder/data/IO/muonHP_IO_pixelPath_forest_v3.bin'),
decisionThreshold = cms.double(0.21345365047454834),
ptBinEdges = cms.vdouble(0.0, 2.0, 5.0, 10.0, 50.0, 200.0),
decisionThresholds = cms.vdouble(
    0.10667391866445541,  # pT [0, 2)
    0.21345365047454834,  # pT [2, 5)
    0.5016972422599792,  # pT [5, 10)
    0.5444226264953613,  # pT [10, 50)
    0.8626133799552917,  # pT [50, 200)
    0.21345365047454834,  # pT [200, inf) - global F2 fallback
)
nFeatures = cms.int32(33),
