# OI general forest: 200 trees, 22 features, .bin md5 78fa350f5572eecb31e3498cb72f51fa
# generated by forest_pipeline.py; paste into HLTrigger/Configuration/python/HLT_75e33/modules/hltPhase2L3OIMuonTrackSelectionHighPurityForest_cfi.py
modelPath = cms.FileInPath('RecoMuon/L3TrackFinder/data/OI/muonHP_OI_seedsPath_forest_v3.bin'),
decisionThreshold = cms.double(0.5891533493995667),
ptBinEdges = cms.vdouble(0.0, 2.0, 5.0, 10.0, 50.0, 200.0),
decisionThresholds = cms.vdouble(
    0.47719821333885193,  # pT [0, 2)
    0.4623990058898926,  # pT [2, 5)
    0.32259517908096313,  # pT [5, 10)
    0.6471585631370544,  # pT [10, 50)
    0.6572598814964294,  # pT [50, 200)
    0.5691716074943542,  # pT [200, inf)
)
nFeatures = cms.int32(22),
