# IO seeds forest: 1250 trees, 33 features, .bin md5 8c936b2ef077e5501f18c6676b5c0cc1
# generated by forest_pipeline.py; paste into HLTrigger/Configuration/python/HLT_75e33/modules/hltPhase2MuonIOTrackSelectionHighPurityForest_cfi.py
modelPath = cms.FileInPath('RecoMuon/L3TrackFinder/data/IO/muonHP_IO_seedsPath_forest_v3.bin'),
decisionThreshold = cms.double(0.17353090643882751),
ptBinEdges = cms.vdouble(0.0, 2.0, 5.0, 10.0, 50.0, 200.0),
decisionThresholds = cms.vdouble(
    0.03589987754821777,  # pT [0, 2)
    0.16624124348163605,  # pT [2, 5)
    0.34693241119384766,  # pT [5, 10)
    0.47059762477874756,  # pT [10, 50)
    0.5600723624229431,  # pT [50, 200)
    0.8556238412857056,  # pT [200, inf)
)
nFeatures = cms.int32(33),
